### ISSUE TITLE
Question: How to work with nested configurations - binding?

### ISSUE THREAD

**Issue by siyb** [cfg4j/cfg4j-sample-apps#3]
Given the following config:

```
config:
  http:
    interfaces:
      - host: "test"
        port: 6666
      - host: "test1"
        port: 1234
```

and the corresponding config definition:

```
interface Config {
    Http http();
    interface Http {
        List<Interface> interfaces();
        interface Interface {
            String host();
            Integer();
        }
    }
}
```
    
How do I bind the Config during runtime,

`configurationProvider.bind("config", Config.class);`

does not seem to work. Is the only option to use `configurationProvider.getProperty` in this case?
